### ISSUE TITLE
kivy / cython dependency bug

### ISSUE THREAD

**Issue by gcentauri** [pfassina/callllama#2]
i get this error trying to install with both requirements.txt

```
Collecting Kivy==1.10.1 (from -r requirements_windows.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/7d/8b/89d220b7f96dc2662b81319067f679b4cd73cda66f4aa850db5b6c6cfc7a/Kivy-1.10.1.tar.gz
    Complete output from command python setup.py egg_info:
    Using distutils
    
    Cython is missing, it's required for compiling kivy !
    
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ha0pqkm7/Kivy/setup.py", line 232, in <module>
        from Cython.Distutils import build_ext
    ModuleNotFoundError: No module named 'Cython'
```
related issue on kivy - https://github.com/kivy/kivy/issues/5375

**Comment by gcentauri** [comment]
dunno if this matters anymore, just cleaning up my GH
